# Generated by Django 4.0.2 on 2022-02-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado_geral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Título', models.CharField(max_length=255)),
                ('Descrição', models.TextField()),
                ('Status', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Em_andamento', 'Em_andamento'), ('Concluído', 'Concluído')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
