# Generated by Django 4.0.1 on 2022-02-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados_geral', '0002_chamado_geral_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado_geral',
            name='Arquivo',
            field=models.FileField(blank=True, null=True, upload_to='anexos/'),
        ),
    ]
