# Generated by Django 4.0.1 on 2022-02-18 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamados_geral', '0008_alter_chamado_geral_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado_geral',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
